version: 0.2
phases:
  # pre_build:
  #   commands:

  build:
    commands:
      - cd frontend
      - npm install
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: frontend/build

cache:
  paths:
    - '/root/.m2/**/*'