version: 0.0
os: linux

files:
  - source: server/server
    destination: /
  - source: scripts/
    destination: /scripts

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
  BeforeInstall:
    - location: scripts/before_install.sh
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120