version: 0.0
os: linux

files:
  - source: scripts/
    destination: /scripts

hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
  BeforeInstall:
     - location: scripts/before_install.sh
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 120