version: 0.0
os: linux

files:
  - source: scripts/
    destination: /scripts

hooks:
  ApplicationStop:
    - location: stop_container.sh
  BeforeInstall:
     - location: before_install.sh
  ApplicationStart:
    - location: start_container.sh
      timeout: 120