version: 0.2

phases:
  # pre_build:
  #   commands:

  build:
    commands:
      - cd backend/server
      - go get -d ./...
      - go build
artifacts:
  files:
    - '**/*'
  base-directory: backend