CREATE TABLE post(
    id 			int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title 		varchar(255) UNIQUE,
  	slug 		varchar(255) UNIQUE,
  	img 		varchar(255),
    summary 	varchar(255),
    content 	text,
  	raw_content text
);

CREATE TABLE tag(
    id 		int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value 	varchar(50)
);

CREATE TABLE post_tag(
    post_id int REFERENCES post (id) ON DELETE CASCADE,
    tag_id	int REFERENCES tag (id) ON DELETE CASCADE
);

CREATE VIEW post_to_tag AS
    SELECT post.title, post.id as post_id, tag.id as tag_id, tag.value
    FROM post, post_tag, tag
    WHERE post.id = post_tag.post_id AND tag.id = post_tag.tag_id;